### ISSUE TITLE
issues in drone parsing

### ISSUE THREAD

**Issue by computron** [hackingmaterials/MatMethods#12]
@matk86 I am looking over the results of the MatMethods drone parsing a run with both "relax1" and "relax2" jobs and see several issues:

1. calcs_reversed.0.completed_at is *earlier* than calcs_reversed.1.completed_at. Remember that the zero index is supposed to be the later job. Do you know why this is? Other properties might be OK and in the right order. e.g. I checked the final energies and the zero index indeed gives the correct final energy of relax2. But the "completed_at" looks wrong, and maybe other things are too? Can you check this?

2. the "run_stats" (root key) has sub-keys "standard" and "relax2". This should be "relax1" (not standard) and "relax2". Mainly, I feel the sub-keys in "run_stats" should match the labels in "calcs_reversed.x.task.name" if the latter are present.

3. In the root "output" key, there is an "outcar" subkey. I would delete this outcar subkey; it is redundant with calcs_reversed.0.output.outcar. Besides, it looks like it is using the *wrong* outcar (the calcs_reversed.1.output.outcar)!!!

You should be able to reproduce the above errors by running your drone on:
/MatMethods/matmethods/vasp/tests/reference_files/Si_structure_optimization_relax2/outputs

However, in case you are not seeing the above problems, let me know. The actual problems I saw were in a directory at NERSC (/global/project/projectdirs/m2439/matmethods_test/scratch/block_2016-04-15-21-06-54-570920/launcher_2016-04-15-21-06-54-727961) and I will need to give you access.

**Comment by matk86** [comment]
I will look into it

**Comment by matk86** [comment]
1. all the files in the directory: /MatMethods/matmethods/vasp/tests/reference_files/Si_structure_optimization_relax2/outputs, yield same value for str(datetime.datetime.fromtimestamp(os.path.getmtime(vasprun_file))).

2. fixed the runstats taskname issue in the post_process method

3. removed outcar key from the root 'output', moved it to calcs_reversed.x.output.outcar(this was not here before)

the fixes are in the latest pull request

**Comment by matk86** [comment]
please dont merge now, found some more bugs..fixing it

**Comment by computron** [comment]
ok - let me know when finished. I will also send over the directory with the completed_at issue now

**Comment by matk86** [comment]
ok thanks

**Comment by matk86** [comment]
fixed
