### ISSUE TITLE
ToDBTask() will only work with matmethods drone

### ISSUE THREAD

**Issue by computron** [hackingmaterials/MatMethods#15]
@shyamd - the purpose of your suggestion to add ToDBTask() was to make the db task drone-agnostic. But this line:

```
t_id, task_doc = drone.assimilate_return_task_doc(calc_dir)
```

assumes the drone has a method called ``assimilate_return_task_doc``. Actually, only the MatMathods drone has this method. It is not a general method of drones. This means that only the MatMethods drone can in practice be used here.

Can you figure out a solution, perhaps working with @shyuep in case changes are desired in underlying pymatgen?

**Comment by shyamd** [comment]
Yup, You're right. That is MM specific. I think the whole DB insertion in the drone clashes with what the drone is supposed to do, which is assimilate the calculation data into a pymatgen ( or generic python dict) object. The matgendb and the MM Drone both do the DB insertion as well. To me it makes more sense for the DB insertion to be part of the fire task. That way the drone would always return a doc using assimilate and the fire task would take care of appending DB specific information such as task_id, and inserting into the appropriate db: json file, mongoldb, ... who knows in the future? This would restrict changes to MM, but would break with the matgendb.creator paradigm.

**Comment by computron** [comment]
I agree that the Drone should only be responsible for returning a JSON document and not even need a db connection. i.e., if I implement a new Drone, I don't worry about the DB stuff at all. The db insertion could be handled either by MatMethods, or even within pymatgen-db itself as a separate layer in "hive" or "queen" etc. that utilizes drones but takes care of the higher-level DB stuff. e.g., the simulate_mode vs. db insertion stuff is all implemented outside of specific drone instances.

Would require @shyuep 's input and blessing ...

**Comment by computron** [comment]
FYI a temporary solution is to simply use the assimilate() method and get back the task id. Then use the task_id + database credentials to fetch the task_doc from the database. Then you don't need the assimilate_return_task_doc() method. But I find that clunky (e.g., to reconnect to the database manually and perform a query for data that you just had) and sometimes there are delays in writing to databases so that's why I prefer being able to get the task_doc within a dedicated function.

**Comment by shyamd** [comment]
Alright. For now, since we have only one drone. It doesn't seem to break current functionality. I'm working on breaking DB access out of the drone and into the DBTask as well as refactoring the drone around a bit. Do you want me to push the temp fix into MM or just wait for new drone/DbTask?

**Comment by computron** [comment]
>> I'm working on breaking DB access out of the drone and into the DBTask as well as refactoring the drone around a bit. 
Ok but you might want to run the changes by Shyue. He is the boss for pymatgen/pymatgen-db

>> Do you want me to push the temp fix into MM or just wait for new drone/DbTask?
Up to you. I am not depending on the fix anytime soon.

**Comment by matk86** [comment]
i guess the latest merge fixes this issue ?

**Comment by computron** [comment]
Ok I am closing this. Looks like the @matk86 changes make this more flexible. Only issue is that the assimilate() function for drones is not so well specified. In some drones it returns a task doc (which is used here), in others when there is a database insertion it might only return a task id (which I personally hate). Oh well, let's at least try to be consistent ourselves and make sure assimilate() returns a full task doc.

**Comment by shyamd** [comment]
Ok, it's official. Kiran is @matk86 is amazing. I was working on something similar, but that was record time. 

The assimilate function is supposed to return a PMG object according to abstract class. Returning a task id seems out of line with what PMG drone's own documentation. I agree we should be consistent and all MatMethod drones should return a doc. Fire task is what makes the doc into a task_doc by adding on the appropriate information.

**Comment by shyuep** [comment]
Excellent. Hopefully that means I can retire from coding.

**Comment by shyuep** [comment]
Just a note that for drones, technically, VaspDrone is actually a strange beast. Unlike proper drones that are used to parallel assimilate a large number of directories via the BorgQueen, the VaspDrone is typically used by MP (and I suppose MatMethods) in a serial fashion per run. As a general design principle, there is no real reason why such a class needs to inherit the abstract drone. 

This is different in the case of people who are not using FireWorks, but are nonetheless needing to assimilate runs into a db after running say hundreds of calculations.
