### ISSUE TITLE
why is "magmom" a required parameter for WriteVaspSOCFromPrev?

### ISSUE THREAD

**Issue by computron** [hackingmaterials/MatMethods#23]
@matk86 - see title

It looks like the from_prev_run() method is perfectly happy to not need a magmom parameter, so why require it in order to use WriteVaspSOCFromPrev?

**Comment by matk86** [comment]
According to vasp recommendations soc calculations need to run with previous chgcar without the magnetic moment info. write from previous basically takes the structure and chgcar from previous non magnetic calculation and combine it with the provided magmom to run soc calculations
