### ISSUE TITLE
TransmuterFW serialization issue

### ISSUE THREAD

**Issue by montoyjh** [hackingmaterials/MatMethods#24]
## System

* Version: master
* Python version: 2.7
* OS version: GNU/Linux

## Summary

* Serialization of transmuter FW

The transmuter FW fails to serialize because the parameter "transformations" is a list of classes, rather than instances of classes (which are then constructed into instances with the transformation parameters).  In the FireWorks recursive_dict procedure, the class (which has an "as_dict" attribute) fails to execute the as_dict method since it's not an instance.

## Example code

```python
from matmethods.vasp.fireworks.core import TransmuterFW
from pymatgen.transformations.standard_transformations import \
    DeformStructureTransformation
from pymatgen.util.testing import PymatgenTest

structure=PymatgenTest.get_structure("Si")
fw = TransmuterFW(name="elastic deformation",
                  structure=structure,
                  transformations=[DeformStructureTransformation],
                  transformation_params=[
                      {"deformation": [[1, 0, 0.01],
                                       [0, 1, 0],
                                       [0, 0, 1]]}])

```

## Error message

```
File "/global/u1/m/montoyjh/jhm_test/codes/fireworks/fireworks/utilities/fw_serializers.py", line 70, in recursive_dict
    return recursive_dict(obj.as_dict(), preserve_unicode)
TypeError: unbound method as_dict() must be called with DeformStructureTransformation instance as first argument (got nothing instead)
```

**Comment by matk86** [comment]
transformations should be a list of class names i.e  transformations=['DeformStructureTransformation'] insteadf of  transformations=[DeformStructureTransformation].

**Comment by computron** [comment]
@matk86 can you clarify the docs of the class?

**Comment by montoyjh** [comment]
Ah, thanks.

**Comment by matk86** [comment]
updated the doc
