### ISSUE TITLE
issue with wf_elastic_constant

### ISSUE THREAD

**Issue by albalu** [hackingmaterials/MatMethods#28]
## Elastic constant workflow for ['mp-5094', 'mp-30452']

* Version: latest
* Python version: 2.7
* OS version: Edison

## Summary

* raised error when trying to add elastic constant workflow for these two materials (I tried them separately, both have problems)

## Example code

```python
from matmethods.vasp.workflows.presets.core import *
list = ['mp-5094', 'mp-30452']	# Co2Ge3Se3, DyNiBi
for mpid in list:
	structure = mpr.get_structure_by_material_id(mpid)
	wf = wf_elastic_constant(structure)
```

## Error message

```
Traceback (most recent call last):
  File "run_matmethods.py", line 25, in <module>
    wf2 = wf_elastic_constant(structure)
  File "/global/project/projectdirs/m2439/alireza/MatMethods/codes/MatMethods/matmethods/vasp/workflows/presets/core.py", line 149, in wf_elastic_constant
    vasp_cmd = c.get("VASP_CMD", VASP_CMD)
AttributeError: 'NoneType' object has no attribute 'get'
```

Please note that I ran the above script for Si and GaAs w/o problems.

**Comment by computron** [comment]
Hi alireza

This is my mistake but the fix is one line of code. Id like you to attempt to fix and submit a pull request. If you cannot figure it out let me know

Best,
Anubhav

**Comment by albalu** [comment]
Sorry I pushed instead of a pull request but it seems to be ok.

**Comment by computron** [comment]
Thanks! For minor fixes like this, pushing is OK and probably more efficient.

I will likely try to design a simple unit test for these preset workflows to make sure that basic things like this don't break in the future.
